# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
parse <- function(file_name) {
    .Call('_rds2cpp_parse', PACKAGE = 'rds2cpp', file_name)
}

#' @export
write <- function(x, file_name) {
    .Call('_rds2cpp_write', PACKAGE = 'rds2cpp', x, file_name)
}

