# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
parse_rds <- function(file_name, parallel) {
    .Call('_rds2cpp_parse_rds', PACKAGE = 'rds2cpp', file_name, parallel)
}

#' @export
parse_rda <- function(file_name, parallel) {
    .Call('_rds2cpp_parse_rda', PACKAGE = 'rds2cpp', file_name, parallel)
}

#' @export
parse_length <- function(raw) {
    .Call('_rds2cpp_parse_length', PACKAGE = 'rds2cpp', raw)
}

#' @export
parse_single_string <- function(raw) {
    .Call('_rds2cpp_parse_single_string', PACKAGE = 'rds2cpp', raw)
}

#' @export
write_rds <- function(x, file_name, parallel) {
    .Call('_rds2cpp_write_rds', PACKAGE = 'rds2cpp', x, file_name, parallel)
}

#' @export
write_rda <- function(x, file_name, parallel) {
    .Call('_rds2cpp_write_rda', PACKAGE = 'rds2cpp', x, file_name, parallel)
}

