// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// parse_rds
Rcpp::RObject parse_rds(std::string file_name, bool parallel);
RcppExport SEXP _rds2cpp_parse_rds(SEXP file_nameSEXP, SEXP parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< std::string >::type file_name(file_nameSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_rds(file_name, parallel));
    return rcpp_result_gen;
END_RCPP
}
// parse_rda
Rcpp::RObject parse_rda(std::string file_name, bool parallel);
RcppExport SEXP _rds2cpp_parse_rda(SEXP file_nameSEXP, SEXP parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< std::string >::type file_name(file_nameSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_rda(file_name, parallel));
    return rcpp_result_gen;
END_RCPP
}
// parse_length
double parse_length(Rcpp::RawVector raw);
RcppExport SEXP _rds2cpp_parse_length(SEXP rawSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type raw(rawSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_length(raw));
    return rcpp_result_gen;
END_RCPP
}
// parse_single_string
Rcpp::RObject parse_single_string(Rcpp::RawVector raw);
RcppExport SEXP _rds2cpp_parse_single_string(SEXP rawSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type raw(rawSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_single_string(raw));
    return rcpp_result_gen;
END_RCPP
}
// write_rds
Rcpp::RObject write_rds(Rcpp::RObject x, std::string file_name, bool parallel);
RcppExport SEXP _rds2cpp_write_rds(SEXP xSEXP, SEXP file_nameSEXP, SEXP parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type file_name(file_nameSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(write_rds(x, file_name, parallel));
    return rcpp_result_gen;
END_RCPP
}
// write_rda
Rcpp::RObject write_rda(Rcpp::List x, std::string file_name, bool parallel);
RcppExport SEXP _rds2cpp_write_rda(SEXP xSEXP, SEXP file_nameSEXP, SEXP parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type file_name(file_nameSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(write_rda(x, file_name, parallel));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rds2cpp_parse_rds", (DL_FUNC) &_rds2cpp_parse_rds, 2},
    {"_rds2cpp_parse_rda", (DL_FUNC) &_rds2cpp_parse_rda, 2},
    {"_rds2cpp_parse_length", (DL_FUNC) &_rds2cpp_parse_length, 1},
    {"_rds2cpp_parse_single_string", (DL_FUNC) &_rds2cpp_parse_single_string, 1},
    {"_rds2cpp_write_rds", (DL_FUNC) &_rds2cpp_write_rds, 3},
    {"_rds2cpp_write_rda", (DL_FUNC) &_rds2cpp_write_rda, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_rds2cpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
